import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillFacebook,
} from "react-icons/ai";
import Image from "next/image";
import wave from "../public/wave.png";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import { useState } from "react";

export default function Home() {
  const [darkMode,setDarkMode]=useState(false)
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Mr Waseem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-slate-100 dark:bg-gray-900 px-4 sm:px-20">
        <section className=" min-h-min mb-10">
          <nav className="pt-10 flex justify-between ">
            <h1 className=" text-lg sm:text-xl font-bold dark:text-white">
              DevelopedByWaseem
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className=" transition duration-300 ease-in-out  cursor-pointer fill-gray-500 text-2xl hover:fill-gray-900 transform hover:-translate-y-1 hover:scale-110 dark:fill-white "
                  onClick={() => setDarkMode(!darkMode)}
                />
              </li>
              <li>
                <a
                  href="#"
                  className="transition duration-500 ease-in-out text-white py-2 px-4 rounded-md ml-8 bg-blue-500 hover:bg-blue-800 transform hover:-translate-y-1 hover:scale-110   "
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-8 ">
            <h2 className=" transition duration-500 ease-in-out text-4xl sm:text-5xl py-2 text-teal-900 font-medium dark:text-slate-300 transform hover:-translate-y-1 hover:scale-110">
              Waseem Kashif
            </h2>
            <h3 className="text-2xl py-2 dark:text-slate-400">Web Developer</h3>
            <div className="text-left mx-auto">
              <p className="text-md py-2 leading-6 text-gray-800 dark:text-slate-400">
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni
                dicta quisquam assumenda similique, officia corporis
                necessitatibus rerum soluta quibusdam suscipit beatae
                cupiditate, cumque expedita quos aut aliquid sunt culpa!
                Eveniet?
              </p>
            </div>
          </div>
          <div className="flex justify-center gap-5 text-3xl">
            <AiFillTwitterCircle className=" fill-cyan-500 cursor-pointer" />
            <AiFillLinkedin className=" fill-blue-900 cursor-pointer" />
            <AiFillYoutube className=" fill-red-700 cursor-pointer" />
            <AiFillFacebook className=" fill-blue-900 cursor-pointer" />
          </div>
          <div className=" relative mx-auto overflow-hidden bg-gradient-to-t from-fuchsia-400 to-blue-950 rounded-full w-80 h-80 mt-10  ">
            <Image alt="wave" src={wave} fill className=" object-cover" />
          </div>
        </section>
        {/* Second-section */}
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-slate-100">
              Services I offer{" "}
            </h3>

            <p className="text-md leading-8 text-gray-800 dark:text-slate-400">
              Lorem ipsum dolor sit amet{" "}
              <span className="text-blue-700"> adipisicing elit</span>.
              Asperiores error delectus est! Ipsam pariatur magnam nostrum ex
              libero culpa ab quis ad eligendi!
              <span className="text-blue-700">Nihil nulla</span> rerum quis eum
              labore eveniet! Lorem, ipsum dolor sit amet consectetur
              adipisicing elit. Rem libero harum ipsum excepturi non, autem
              totam blanditiis. Dolores tempore nobis tempora ipsa reprehenderit
              dolorem dignissimos dolore illo. Est, magni exercitationem?
            </p>
          </div>
          <div className="grid grid-cols-1  md:grid-cols-2 lg:grid-cols-3 md:gap-8">
            <div className="flex flex-col shadow-xl p-5 md:p-10  bg-fuchsia-300 rounded-lg my-5 md:my-10 items-center  ">
              <Image alt="design" src={design} width={100} height={100} />
              <h3 className="font-bold text-xl pb-3">Beautiful designs</h3>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Asperiores eaque, quam neque dolorem voluptates ullam facilis
                quas quaerat alias ratione praesentium velit, beatae adipisci,
                in eum. Nisi eligendi inventore maiores.
              </p>
              <h4 className="text-sky-900 py-4   font-bold">
                Design tools I use{" "}
              </h4>

              <p className="text-gray-800 text-py-1 ">Illisutrator</p>
              <p className="text-gray-800 text-py-1">Photoshop</p>
              <p className="text-gray-800 text-py-1 ">VS Code</p>
              <p className="text-gray-800 text-py-1">Figma</p>
            </div>
            <div className="flex flex-col shadow-xl p-10  bg-fuchsia-300 rounded-lg my-10 items-center">
              <Image alt="image" src={code} width={100} height={100} />
              <h3 className="font-bold text-xl pb-3">Expert Coding</h3>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Asperiores eaque, quam neque dolorem voluptates ullam facilis
                quas quaerat alias ratione praesentium velit, beatae adipisci,
                in eum. Nisi eligendi inventore maiores.
              </p>
              <h4 className="text-sky-900 py-4   font-bold">
                Design tools I use{" "}
              </h4>

              <p className="text-gray-800 text-py-1 ">Illisutrator</p>
              <p className="text-gray-800 text-py-1">Photoshop</p>
              <p className="text-gray-800 text-py-1 ">VS Code</p>
              <p className="text-gray-800 text-py-1">Figma</p>
            </div>
            <div className=" flex flex-col items-center shadow-xl p-10  bg-fuchsia-300 rounded-lg my-10">
              <Image src={consulting} width={100} height={100} />
              <h3 className="font-bold text-xl pb-3">Communication</h3>
              <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Asperiores eaque, quam neque dolorem voluptates ullam facilis
                quas quaerat alias ratione praesentium velit, beatae adipisci,
                in eum. Nisi eligendi inventore maiores.
              </p>
              <h4 className="text-sky-900 py-4   font-bold">
                Design tools I use{" "}
              </h4>

              <p className="text-gray-800 text-py-1 ">Illisutrator</p>
              <p className="text-gray-800 text-py-1">Photoshop</p>
              <p className="text-gray-800 text-py-1 ">VS Code</p>
              <p className="text-gray-800 text-py-1">Figma</p>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
